apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-configuration-role-binding
  namespace: mysql-snowflake-test
subjects:
- kind: ServiceAccount
  name: debezium-connect-cluster-connect
  namespace: mysql-snowflake-test
roleRef:
  kind: Role
  name: connector-configuration-role
  apiGroup: rbac.authorization.k8s.io